robot_ids: ['0','1']
robot_types: {'0':1,'1':2}
robot_ranges: {'0':20,'1':20}
robot_map: [{'id': 0, 'comm_model': 'disc', 'connections': [1]}, {'id': 1, 'comm_model': 'disc', 'connections': [0]}]
topics: [{'name': 'base_pose_ground_truth', 'pkg': 'nav_msgs', 'message_type': 'Odometry', 'message_pkg': 'nav_msgs', 'remap': 1, 'ns': 'robot'},{'name': 'signal_strength', 'pkg': 'recurrent_connectivity', 'message_type': 'SignalStrength', 'message_pkg': 'recurrent_connectivity', 'remap': 1, 'ns': 'robot'},{'name': 'chosen_point', 'pkg': 'recurrent_connectivity', 'message_type': 'ChosenPoint', 'message_pkg': 'recurrent_connectivity', 'remap': 1, 'ns': 'robot'},{'name': 'rendezvous_points', 'pkg': 'recurrent_connectivity', 'message_type': 'RendezvousPoints', 'message_pkg': 'recurrent_connectivity', 'remap': 1, 'ns': 'robot'},{'name': 'received_data', 'pkg': 'recurrent_connectivity', 'message_type': 'BufferedData', 'message_pkg': 'recurrent_connectivity', 'remap': 1, 'ns': 'robot'}]
topic_remaps: [{'name': 'karto_out', 'pkg': 'nav2d_karto', 'from': 'karto_out', 'to': '/karto_out', 'message_type': 'LocalizedScan', 'message_pkg': 'nav2d_msgs', 'remap': 1}]
shared_topics: {'0':{'1': {'received_data':'BufferedData','rendezvous_points':'RendezvousPoints','chosen_point':'ChosenPoint'}},'1':{'0': {'received_data':'BufferedData','rendezvous_points':'RendezvousPoints','chosen_point':'ChosenPoint'}}}

map_image_path: '/home/masaba/stage_ws/src/recurrent_connectivity/world/offices.png'
world_center: [40.0,15.0]
world_scale: 10
map_pose: [39.85,14.55]

#robot_ids: ['0','1','2','3','4']
#robot_types: {'0':1,'1':2,'2':2,'3':3,'4':4}
#robot_ranges: {'0':10,'1':10,'2':10,'3':5,'4':5}
#robot_map: [{'id': 0, 'comm_model': 'disc', 'connections': [1,2]}, {'id': 1, 'comm_model': 'disc', 'connections': [0,3]},{'id': 2, 'comm_model': 'disc', 'connections': [0,4]},{'id': 3, 'comm_model': 'disc', 'connections': [1]},{'id': 4, 'comm_model': 'disc', 'connections': [2]}]
#topics: [{'name': 'rendezvous_points', 'pkg': 'finalproject', 'message_type': 'RendezvousPoints', 'message_pkg': 'finalproject', 'remap': 1, 'ns': 'robot'},{'name': 'received_data', 'pkg': 'finalproject', 'message_type': 'BufferedData', 'message_pkg': 'finalproject', 'remap': 1, 'ns': 'robot'}]
#topic_remaps: [{'name': 'karto_out', 'pkg': 'nav2d_karto', 'from': 'karto_out', 'to': '/karto_out', 'message_type': 'LocalizedScan', 'message_pkg': 'nav2d_msgs', 'remap': 1}]
#shared_topics: {'0':{'1': {'received_data':'BufferedData'},'2': {'received_data':'BufferedData'}},'1':{'0': {'received_data':'BufferedData','rendezvous_points':'RendezvousPoints'},'3': {'received_data':'BufferedData'}},'2':{'0': {'received_data':'BufferedData','rendezvous_points':'RendezvousPoints'},'4': {'received_data':'BufferedData'}},'3':{'1': {'received_data':'BufferedData','rendezvous_points':'RendezvousPoints'}},'4':{'2':{'received_data':'BufferedData','rendezvous_points':'RendezvousPoints'}}}
#
#
#map_image_path: '/home/masaba/stage_ws/src/finalproject/world/offices.png'
#world_center: [40.0,15.0]
#world_scale: 10
#map_pose: [39.85,14.55]